### ISSUE TITLE
On Clicking Invoice Fragment Btn, app crashes

### ISSUE THREAD

**Issue by rajitdeb** [PrajjwalDy/dgNiryat#4]
In `HomeFragment`, when `Invoice` button is pressed, it crashes the app.

Screen Recording:

https://github.com/PrajjwalDy/dgNiryat/assets/33742708/8e45d6e1-8c42-4655-ad9e-099befc7b08d

**Comment by rajitdeb** [comment]
@PrajjwalDy This issue requires attention. Please label this issue as "hactoberfest" and "good first issue"

**Comment by rajitdeb** [comment]
Please assign this issue to me. I can solve this issue @PrajjwalDy

**Comment by PrajjwalDy** [comment]
> Please assign this issue to me. I can solve this issue @PrajjwalDy 

Thank you Rajit for the Issues, I'll assign this to you

**Comment by PrajjwalDy** [comment]
Solve other issues too if able

**Comment by rajitdeb** [comment]
> Solve other issues too if able

Yeah sure, i am on it. I am creating all the issues that i am currently experiencing in the app. Please add the "Hactoberfest" label to all of them so that my contributions are marked valid @PrajjwalDy

**Comment by PrajjwalDy** [comment]
> > Solve other issues too if able
> 
> Yeah sure, i am on it. I am creating all the issues that i am currently experiencing in the app. Please add the "Hactoberfest" label to all of them so that my contributions are marked valid @PrajjwalDy 

Ok I'll label all the issues

**Comment by rajitdeb** [comment]
Fixed the issue in PR (#8). Please review the changes and merge @PrajjwalDy
